### ISSUE TITLE
[Bug]: Molecules> Textarea >Suggestion list: issue with the typing to safari 15.6.1 version.

### ISSUE THREAD

**Issue by GaroGabrielyan** [softconstruct/gene-ui-components#8] opened 2023-11-20 08:08 UTC
### Component

Textarea

### Describe the bug

The user cannot type text in this version (Safari 15.6.1).

### To Reproduce

1. Open Storybook on Safari 15.6.1 version.
2. Click on Molecules.
3. Select Textarea and try typing text.

### Expected behavior

The user should be able to type the text.

### Package version

v2.10.0

### Desktop

. OS: macOS
. Browser & version: Safari 15.6.1

**Comment by hamikhambardzumyan** [comment] 2024-02-08 08:14
Closing this issue, as [for each browser we support the current and previous major releases only](https://geneui-storybook.softconstruct.com/?path=/docs/introduction--docs#supported-browsers). At this moment latest version of the Safari browser is 17 and the previous is 16. The issue is about the 15.6.1 version.

[Here is a link to the Safari browser release notes](https://developer.apple.com/documentation/safari-release-notes).

**Closed by hamikhambardzumyan** 2024-02-08 08:14 UTC
Labels: type / bug, phase / exploring
